<?php

namespace Paytrail\PaymentService\Ui\DataProvider;

use Magento\Backend\Model\Url;
use Magento\Framework\Serialize\SerializerInterface;

class RecurringPaymentForm extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    /**
     * @var array
     */
    private $loadedData;

    /**
     * @var \Paytrail\PaymentService\Model\ResourceModel\Subscription\CollectionFactory
     */
    private $collectionFactory;
    /**
     * @var Url
     */
    private $url;
    /**
     * @var SerializerInterface
     */
    private $serializer;

    public function __construct(
                                                                        $name,
                                                                        $primaryFieldName,
                                                                        $requestFieldName,
        \Paytrail\PaymentService\Model\ResourceModel\Subscription\CollectionFactory $collectionFactory,
        SerializerInterface                                             $serializer,
        Url                                                             $url,
        array                                                           $meta = [],
        array                                                           $data = []
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
        $this->collectionFactory = $collectionFactory;
        $this->url = $url;
        $this->serializer = $serializer;
    }

    /**
     * @return array
     */
    public function getData()
    {
        if (isset($this->loadedData)) {
            return $this->loadedData;
        }

        $this->loadedData = [];
        foreach ($this->getCollection() as $subscription) {
            $this->prepareLinks($subscription);
            $this->loadedData[$subscription->getId()] = $subscription->getData();
        }

        return $this->loadedData;
    }

    public function addFilter(\Magento\Framework\Api\Filter $filter)
    {
        if ($filter->getField() == 'entity_id') {
            $filter->setField('main_table.entity_id');
        }

        parent::addFilter($filter); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Paytrail\PaymentService\Model\ResourceModel\Subscription\Collection
     */
    public function getCollection()
    {
        if (!$this->collection) {
            $this->collection = $this->collectionFactory->create();
            $this->joinProfilesToCollection();
        }

        return $this->collection;
    }

    /**
     * @param \Paytrail\PaymentService\Model\Subscription $subscription
     */
    private function prepareLinks($subscription)
    {
        $subscription->setData(
            'profile_link',
            $this->createLinkData(
                'recurring_payments/profile/edit',
                ['id' => $subscription->getRecurringProfileId()],
                $subscription->getProfileName()
            )
        );
    }

    private function joinProfilesToCollection()
    {
        $this->collection->join(
            ['rpp' => 'recurring_payment_profiles'],
            'main_table.recurring_profile_id = rpp.profile_id',
            ['profile_name' => 'name']
        );
    }

    private function createLinkData(string $path, array $params, string $linkText)
    {
        return [
            'link_text' => $linkText,
            'link' => $this->url->getUrl(
                $path,
                $params
            )
        ];
    }
}
