<?php
/*
 *  Copyright © 2024 GoodAhead. All rights reserved.
 */

declare(strict_types=1);

use Goodahead\HyvaCheckout\ViewModel\SkipPaymentRedirect;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SkipPaymentRedirect $viewModel */

$viewModel = $viewModels->require(SkipPaymentRedirect::class)
?>

<?php
/** Rewrite KM2-2264 start */
if ($viewModel->isSkipPaymentRedirectEnabled()): ?>
    <div class="hidden"></div>
<?php else: ?>
    <div class="flex flex-col h-full items-center justify-center text-center text-xl space-y-5">
        <p class="text-2xl">
            <?= $escaper->escapeHtml(__('Order process completed successfully.')) ?>
        </p>

        <p>
            <?= $escaper->escapeHtml(__('You are being redirected, please wait...')) ?>
        </p>
    </div>
<?php endif; ?>
